CREATE DATABASE QLQCF
GO
USE QLQCF
GO
CREATE TABLE NguoiDung 
	( Id int IDENTITY(1,1) PRIMARY KEY,
	  TaiKhoan NVARCHAR(50),
	  MatKhau NVARCHAR(50)
	  HoTen NVARCHAR(100),
	  NgaySinh DATE,
	  GioiTinh int,
	  DiaChi NVARCHAR(50),
	  Sdt NVARCHAR(50),
	  VaiTro int)
GO
CREATE TABLE NCC 
	( Id int IDENTITY(1,1) PRIMARY KEY,
	  TenNCC NVARCHAR(100),
	  DiaChi NVARCHAR(50),
	  Sdt NVARCHAR(50),
	  Email NVARCHAR(50))
GO
CREATE TABLE HangHoa 
	(Id int IDENTITY(1,1) PRIMARY KEY,
	 TenH NVARCHAR(100),
	 SoLuong int,
	 HSD DATE,
	 DonViTinh NVARCHAR(50),
	 DonGia FLOAT)
GO
CREATE TABLE PHIEUNHAP 
	  ( Id int IDENTITY(1,1) PRIMARY KEY,
	  IdNCC int FOREIGN KEY REFERENCES NCC(Id),
	  IdNV int FOREIGN KEY REFERENCES NGUOIDUNG(Id),
	  NgayNhap DATE,
	  TongTien FLOAT)
GO
 CREATE TABLE CTPN
	   (Id int IDENTITY(1,1) PRIMARY KEY,
	    IdPN int FOREIGN KEY REFERENCES PHIEUNHAP(Id),
		IdH int FOREIGN KEY REFERENCES HANGHOA(Id),
	    SoLuong INT)
GO
CREATE TABLE PHIEUXUAT 
	  ( Id int IDENTITY(1,1) primary key,
	   IdNV int FOREIGN KEY REFERENCES NGUOIDUNG(Id),
	   NgayXuat DATE)
GO
CREATE TABLE CTPX 
	( Id int IDENTITY(1,1) PRIMARY KEY,
	  IdPX int FOREIGN KEY REFERENCES PHIEUXUAT(Id),
	  IdH int FOREIGN KEY REFERENCES HANGHOA(Id),
	  SoLuong INT,)
GO
CREATE TABLE SanPham 
	( Id int IDENTITY(1,1) PRIMARY KEY,
	TenSP NVARCHAR(100),
	Mota Text,
	DonGia FLOAT,
	AnhSP NVARCHAR(200))
GO
CREATE TABLE DONHANG
	( Id int IDENTITY(1,1) PRIMARY KEY,
	  IdNV int FOREIGN KEY REFERENCES NGUOIDUNG(Id),
	  NgayDat DATE,
	  TrangThai int,
	  TongTien FLOAT)
GO 
CREATE TABLE CTDH
	(Id int IDENTITY(1,1) PRIMARY KEY,
	 IdDH int FOREIGN KEY REFERENCES DONHANG(Id),
	 IdSP int FOREIGN KEY REFERENCES SANPHAM(Id),
	 SoLuong INT,
	 MoTa Text,
	 GiaTien FLOAT)


--Tính tổng tiền cho phiếu nhập
Create TRIGGER TONG_TIEN_PN ON CTPN
FOR INSERT,UPDATE,DELETE
AS
BEGIN
UPDATE PHIEUNHAP
SET TONGTIEN=(SELECT SUM(CTPN.SOLUONG*HANGHOA.DonGia)
              FROM CTPN,HangHoa
			  WHERE CTPN.IdH=HANGHOA.Id
			  AND CTPN.IdPN=PHIEUNHAP.Id
			  GROUP BY IdPN)
END