//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCCofee.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTPN
    {
        public int Id { get; set; }
        public Nullable<int> IdPN { get; set; }
        public Nullable<int> IdH { get; set; }
        public Nullable<int> SoLuong { get; set; }
    
        public virtual HangHoa HangHoa { get; set; }
        public virtual PHIEUNHAP PHIEUNHAP { get; set; }
    }
}
