//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCCofee.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Giohang1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Giohang1()
        {
            this.ChiTietGioHang = new HashSet<ChiTietGioHang>();
        }
    
        public int ID_GioHang { get; set; }
        public Nullable<int> ID_KhachHang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietGioHang> ChiTietGioHang { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
